name: PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run:
        using: 'docker'
        image: 'Dockerfile'
        entrypoint: 'make'
      - uses: actions/upload-artifact@master
        with:
          name: README.pdf 
          path: README.pdf
